### ISSUE TITLE
Replace test config parsing library

### ISSUE THREAD

**Issue by kaklakariada** [exasol/s3-document-files-virtual-schema#106]
Currently s3-document-files-virtual-schema parses `test_config.yml` with snakeyaml which has security vulnerabilities.
As the file format is quite simple we should replace snakeyaml with Java's property format.

Example:

```yaml
awsProfile: default_mfa
owner: user@exasol.com
s3CacheBucket: user-testdata-cache
```

Proposal: change name of expected file to `test_config.properties`. In case this file does not exist and `test_config.yml` does exists then tests should fail with a helpful error message (e.g. "please migrate from yaml to properties").
